language: python
# with next we get on container based infrastructure, this enables caching
sudo: false
python:
  - 2.7
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  - PLONE_VERSION=4.3.x
  - PLONE_VERSION=5.0.x
matrix:
  allow_failures:
    - env: PLONE_VERSION=5.0.x
dist: trusty
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install --upgrade -r requirements.txt
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - bin/buildout -N -t 20 -c travis.cfg
script:
  - bin/code-analysis
  - bin/coverage run bin/test
  # Run Robot Framework in isolation to avoid test isolation issues.
  - export ROBOTSUITE_PREFIX=ONLYROBOT && bin/test -t ONLYROBOT --all
after_success:
  - pip install -q coveralls python-coveralls==2.5.0
  - coveralls